from common import *
fake = FakeGH()
with sync_playwright() as p:
    b = launch(p); c = ctx(b, fake); pg = page(c, "#/", ".tile")
    pg.wait_for_timeout(1500)
    print("HOME asks:", pg.locator(".ask").count(), "mkchip:", pg.locator(".mkchip").inner_text() if pg.locator(".mkchip").count() else None)
    print("mkcard:", pg.locator("#mkcard").inner_text().replace("\n"," | ") if pg.locator("#mkcard").count() else None)
    print("statcard:", pg.locator(".statcard").first.inner_text().replace("\n"," | "))
    print("h1:", pg.locator("h1").inner_text(), "| tiles:", [t.replace("\n"," / ")[:120] for t in pg.locator(".tile .meta").all_inner_texts()])
    print("week:", [w.replace("\n"," ") for w in pg.locator(".wd").all_inner_texts()])
    print("rows:", pg.locator(".lrow").count(), "requests so far:", len(fake.log))
    pg.goto(B + "#/lesson/" + MATHS); pg.wait_for_selector(".rail"); pg.wait_for_timeout(800)
    print("RAIL:", [t.replace("\n"," / ") for t in pg.locator(".rail button").all_inner_texts()])
    print("clock:", pg.locator(".clock").inner_text().replace("\n"," | "))
    print("items in phase 1:", pg.locator("[data-item]").count(), pg.locator("[data-item]").first.get_attribute("data-item"), "ticks:", pg.locator("[data-tick]").count())
    pg.locator('.rail button[data-phase="m2"]').click(); pg.wait_for_timeout(300)
    print("items in m2:", [e.get_attribute("data-item") for e in pg.locator("[data-item]").all()])
    print("m2 marks inputs:", [(e.get_attribute("max")) for e in pg.locator("input.mk").all()])
    pg.locator('.rail button[data-phase="m3"]').click(); pg.wait_for_timeout(300)
    print("items in m3:", [e.get_attribute("data-item") for e in pg.locator("[data-item]").all()][:4], "iframes", pg.locator("iframe").count())
    print("save:", saveline(pg), "errs:", c.errs, "console:", c.console[:5])
    print("puts:", list(fake.puts))
    pg.goto(B + "#/record"); pg.wait_for_selector(".stats .stat", timeout=30000); pg.wait_for_timeout(500)
    print("RECORD stats:", [t.replace("\n"," ") for t in pg.locator(".stats .stat").all_inner_texts()])
    print("record rows:", pg.locator("table.t tbody tr").count(), "profile h3:", pg.locator(".prose h3").count())
    b.close()
