"""12. Odds and ends: nonsense lesson ids can be saved, Revise badge, Log without a script, Yes: finish logging it, suggestion replies, auto theme in a dark OS, marks max."""
from common import *
import json
with sync_playwright() as p:
    b = launch(p)
    # nonsense lesson id -> a tap writes a session.json for it
    fake = FakeGH(); c = ctx(b, fake); pg = page(c, "#/lesson/does-not-exist", ".rail"); pg.wait_for_timeout(300)
    pg.locator("#clkgo").click(); pg.wait_for_timeout(5500)
    bad = [k for k in fake.puts if "does-not-exist" in k]
    check("a mistyped lesson id does NOT create a lesson folder in the repo", not bad, bad)
    if bad: print("   written:", bad, json.loads(fake.puts[bad[0]])["subject"], json.loads(fake.puts[bad[0]])["date"])
    # Revise badge only after visiting home?
    c2 = ctx(b, FakeGH()); p2 = page(c2, "#/revise", ".rev"); p2.wait_for_timeout(500)
    check("sidebar Revise badge shows the due count when the Revise page is the first page opened", p2.locator("#revbadge").is_visible() and p2.locator("#revbadge").inner_text() == "27", (p2.locator("#revbadge").is_visible(), p2.locator("#revbadge").inner_text()))
    p2.goto(B + "#/lesson/" + MATHS); p2.wait_for_selector(".rail"); p2.wait_for_timeout(800)
    check("badge after opening a lesson first", p2.locator("#revbadge").is_visible(), p2.locator("#revbadge").inner_text())
    p2.goto(B + "#/"); p2.wait_for_selector(".tile"); p2.wait_for_timeout(1500)
    check("badge on the home page shows 27", p2.locator("#revbadge").inner_text() == "27", p2.locator("#revbadge").inner_text())
    print("home revise box:", p2.locator("#homerev").inner_text().replace("\n", " | ")[:200])
    c2.close()
    # Log without a script
    fake = FakeGH(); c = ctx(b, fake); pg = page(c, "#/new", "#newform")
    pg.fill("#n-date", "2026-10-04"); pg.select_option("#n-subj", "chem"); pg.fill("#n-title", "Unscripted chem"); pg.locator("#newform button[type=submit]").click(); pg.wait_for_selector(".rail"); pg.wait_for_timeout(1000)
    print("new lesson route:", pg.evaluate("location.hash"), "| title:", pg.locator("h1").inner_text(), "| status:", saveline(pg))
    check("Log without a script for a date that already has a scripted lesson: lands on the EXISTING scripted lesson (title is the script's), the typed title is lost", pg.locator("h1").inner_text() != "Unscripted chem", pg.locator("h1").inner_text())
    pg.wait_for_timeout(5000); s = sess(fake, "2026-10-04-chem")
    print("session for 2026-10-04-chem after 'new':", s and (s["title"], s["status"], s.get("dirty")))
    check("'new' on an existing scripted lesson did not overwrite the script's session title", not s or s["title"] != "Unscripted chem", s and s["title"])
    pg.goto(B + "#/new"); pg.wait_for_selector("#newform"); pg.fill("#n-date", "2026-10-06"); pg.select_option("#n-subj", "maths"); pg.fill("#n-title", "Unscripted maths"); pg.check("#n-makeup"); pg.locator("#newform button[type=submit]").click(); pg.wait_for_selector(".rail"); pg.wait_for_timeout(5500)
    s = sess(fake, "2026-10-06-maths"); print("new unscripted:", s and (s["title"], s["status"], s.get("makeup"), s["date"]))
    check("new unscripted lesson saved at once with title, make-up flag, status", s and s["title"] == "Unscripted maths" and s["makeup"] is True and s["status"] in ("not-started", "in-progress"), s and s["status"])
    check("new unscripted lesson's plan shows the no-script note", "No script for this lesson" in pg.locator("#phasebox").inner_text())
    shot(pg, "plan-unscripted-1366-light", full=False)
    pg.goto(B + "#/"); pg.wait_for_selector(".tile"); pg.wait_for_timeout(1200)
    tile = pg.locator('.tile[data-subject="maths"]').inner_text().replace("\n", " | "); print("maths tile after a new 6 Oct lesson:", tile)
    check("home: today's maths lesson stays up next (not the 6 Oct one)", "Sun 4 Oct" in tile, tile)
    c.close()
    # "Yes: finish logging it" on an ask
    fake = FakeGH(); fake.extra["students/UK-1/lessons/2026-10-03-maths/script.json"] = json.dumps({"id": "2026-10-03-maths", "date": "2026-10-03", "subject": "maths", "title": "Pretend", "phases": [{"id": "p1", "name": "Part", "blocks": [{"type": "text", "html": "<p>Pretend content for the make-up test, long enough to be tickable here.</p>"}]}]}).encode()
    c = ctx(b, fake); pg = page(c, "#/", ".ask"); pg.locator("[data-askyes]").click(); pg.wait_for_selector(".rail"); pg.wait_for_timeout(300)
    check("Yes: finish logging it opens the lesson plan", pg.locator("h1").inner_text() == "Pretend")
    check("...and lands on After the lesson? (it lands on: %s)" % pg.locator('.rail button[aria-current="step"] .nm').inner_text(), pg.locator('.rail button[aria-current="step"]').get_attribute("data-phase") == "_after", pg.locator('.rail button[aria-current="step"]').get_attribute("data-phase"))
    pg.locator('.rail button[data-phase="_after"]').click(); pg.wait_for_timeout(200); pg.locator("#fbform button[type=submit]").click(); pg.wait_for_timeout(2500)
    s = sess(fake, "2026-10-03-maths"); print("finished without minutes:", s["status"], s["time"]["minutes"], s["feedback"].get("at"))
    pg.goto(B + "#/"); pg.wait_for_selector(".tile"); pg.wait_for_timeout(1200)
    check("finishing with no minutes: the home page still asks 'Was it taught?' (taughtOK needs minutes) -> Ali is asked again about a lesson he just finished", pg.locator(".ask").count() == 0, pg.locator(".ask").count())
    print("ask text now:", pg.locator(".ask").inner_text().replace("\n", " | ")[:160] if pg.locator(".ask").count() else "none")
    shot(pg, "home-ask-after-finish-no-minutes-1366-light", full=False)
    c.close()
    # suggestion replies display
    fake = FakeGH(); c = ctx(b, fake); pg = page(c, "#/", ".tile"); pg.locator("[data-suggest]").first.click(); pg.wait_for_selector(".sug-item"); pg.wait_for_timeout(300)
    pg.locator("#sug-list summary").click(); pg.wait_for_timeout(200)
    reps = pg.locator(".sug-reply").all_inner_texts(); print("replies visible:", reps[:5], "count", len(reps))
    check("Your suggestions list shows Claude's replies (Done/Later)", any(r.startswith("Done") for r in reps), reps[:3])
    shot(pg, "suggest-list-open-1366-light", full=False)
    c.close()
    # auto theme in a dark OS
    c = ctx(b, FakeGH(), dark=True); pg = page(c, "#/", ".tile")
    bg = pg.evaluate("getComputedStyle(document.body).backgroundColor"); lab = pg.locator("#theme").inner_text()
    check("Auto in a dark OS: dark colours (rgb(13, 15, 30)) and the label says Auto", bg == "rgb(13, 15, 30)" and "Auto" in lab, (bg, lab))
    c.close()
    # marks input with "4 + 4"
    c = ctx(b, FakeGH()); pg = page(c, "#/lesson/" + MATHS, ".rail"); pg.locator('.rail button[data-phase="m2"]').click(); pg.wait_for_timeout(200)
    mx = pg.locator('[data-item="s6q15"] input.mk').get_attribute("max"); hint = pg.locator('[data-item="s6q15"] .ctl .hint').inner_text()
    check("marks box for a two-part question has a usable max (script says '4 + 4')", mx and mx.strip().isdigit(), (mx, hint))
    pg.locator('[data-item="s6q15"] input.mk').fill("12"); pg.wait_for_timeout(100)
    check("marks above the maximum are accepted silently (12 of '4 + 4')", False, pg.locator('[data-item="s6q15"] input.mk').input_value())
    c.close(); b.close()
summary()
